# Site settings
title: Pride Hearts
tag_text: Pride Hearts
description: A collection of pride hearts to add to your Slack org as emoji.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
